title: "Esup-Pod Documentation"
description: "Video file management platform"
show_downloads: false # indicate whether to provide a download URL
baseurl: "/"
url: "https://EsupPortail.github.io/Esup-Pod"

kramdown:
  auto_ids: true # Add hover anchor links to headers
